events {}

http {
    access_log /dev/stdout;
    error_log /dev/stderr warn;

    server {
        listen 8080;

        location / {
            proxy_pass https://fhir.openelis.org:8443;
            proxy_set_header Host fhir.openelis.org;
            proxy_set_header Accept-Encoding "";
            proxy_ssl_server_name on;
            proxy_ssl_name fhir.openelis.org;
            proxy_ssl_verify off;
            proxy_ssl_certificate /run/hapi-client.pem;
            proxy_ssl_certificate_key /run/hapi-client.pem;
            sub_filter_types application/fhir+json application/json;
            sub_filter_once off;
            sub_filter
                "http://fhir.openelis.org:8080/fhir"
                "http://hapi-mtls-proxy:8080/fhir";
        }
    }
}
